# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  #adapter: postgresql
  adapter: postgis
  host: "/var/run/postgresql"
  encoding: unicode
  database: gis
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  prepared_statements: true

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
