#!/usr/bin/ansible-playbook
---
- name: "Creates database tables"
  hosts: "all"
  user: "root"
  become: true
  become_user: "postgres"
  vars:
    temp_dir: "/tmp/ansible-postgres"
    temp_file: "{{temp_dir}}/5_views.sql"
  tasks:
  - assert:
      msg: "Use --limit!"
      that: "ansible_limit is defined"

  - file:
      path: "{{temp_dir}}"
      state: "directory"

  - copy:
      src: "../db/5_views.sql"
      dest: "{{temp_file}}"

  - name: "run SQL script"
    shell:
      cmd: "/usr/bin/psql --echo-all --dbname {{db.name}} <{{temp_file}}"
    register: "psql"

  - debug:
      var: "psql.stderr_lines" 
