#!/usr/bin/ansible-playbook
---
- name: "Updates Import-Scripts"
  hosts: "all"
  user: "root"
  become: true
  become_user: "importeur"
  vars:
    jetzt: "{{ansible_date_time.date}}_{{ansible_date_time.time|replace(':', '-')}}"
    temp_dir: "/tmp/ansible-importeur"
  tasks:
  - assert:
      msg: "Use --limit!"
      that: "ansible_limit is defined"
        
  - file:
      path: "{{temp_dir}}"
      state: "absent"

  - git:
      repo: "{{global.git_repo_url}}"
      dest: "{{temp_dir}}"
  #  run_once: true
  # delegate_to: localhost

  # loescht keine Dateien! :-(
  #- copy:
  #    backup: yes
  #    src: "/tmp/test-git-clone/import"
  #    dest: "/home/importeur"
  #    owner: "importeur"
  #    group: "importeur"
 
  - stat:
      path: "/home/importeur/import"
    register: "import_dir"

  - name: "backup"
    command: "mv /home/importeur/import /home/importeur/import.backup{{jetzt}}"
    when: "import_dir.stat.exists"

  # Aendert file permissions :-(
  #- copy:
  #    src: "/tmp/test-git-clone/import"
  #    dest: "/home/importeur"
  #    owner: "importeur"
  #    group: "importeur"

  - name: "mv"
    command: "mv {{temp_dir}}/import /home/importeur/import"

  - file:
      path: "{{temp_dir}}"
      state: "absent"

  #- name: "chown"
  #command: "chown -R importeur: /home/importeur/import"

  #- template:
  #  src: "prerender_tiles.sh.j2"
  #  dest: "/home/importeur/import/notices/prerender_tiles.sh"
  #    owner: "importeur"
  #    group: "importeur"
  #    mode: 0750

  - file:
      path: "/home/importeur/Downloads"
      state: "directory"
      mode: 0770

- name: "root install steps"
  hosts: "all"
  user: "root"
  tasks:
  - name: "Create target dir for file exports" 
    file:
      path: "/var/exports"
      state: "directory"
      mode: 0775
      owner: "importeur"
      group: "importeur"

  - name: "Script for update timestamp and empty tile cache"
    command:
      cmd: "mv /home/importeur/import/notices/empty_tile_cache.sh /root/."

  - name: "file permissions"
    file:
      path: "/root/empty_tile_cache.sh"
      owner: "root"
      group: "root"
      mode: 0700
