#!/usr/bin/ansible-playbook
---
- name: "Switch ICMP/Ping on or off"
  hosts: all
  user: root
  tasks:
  - assert:
      msg: "Use --limit!"
      that: "ansible_limit is defined"

  - debug:
      var: "linux.network.icmp"

  - fail:
    when: "linux.network.icmp is not defined"

  - set_fact:
      binary_digit: "{{ (not linux.network.icmp)|int }}"

  - debug:
      var: "binary_digit"

  - shell: "echo {{binary_digit}} > /proc/sys/net/ipv4/icmp_echo_ignore_all"

  - template:
      src: "sysctl.conf.j2"
      dest: "/etc/sysctl.conf"
      backup: yes
      mode: 0644

