#!/usr/bin/ansible-playbook
---
- name: "Installs all required Ubuntu-APT-Packages"
  hosts: all
  user: root
  tasks:
  - assert:
      msg: "Use --limit!"
      that: "ansible_limit is defined"

  - name: "Get Ubuntu release"
    command: "lsb_release -cs"
    register: "lsb_release_cmd"
    changed_when: False

  - set_fact:
      lsb_release: "{{lsb_release_cmd.stdout}}"

  - debug:
      var: "lsb_release"

  - apt_repository:
      repo: "deb http://apt.postgresql.org/pub/repos/apt/ {{lsb_release}}-pgdg main"
      filename: "postgresql"
      state: "present"
      validate_certs: yes

  - apt_repository:
      repo: "ppa:osmadmins/ppa"
      state: "present"
      validate_certs: yes

  #- apt_repository:
  #    repo: "ppa:kakrueger/openstreetmap"
  #    state: "present"
  #    validate_certs: no

  - apt_key:
      url: "https://www.postgresql.org/media/keys/ACCC4CF8.asc"
      state: "present"

  - apt_key:
      url: "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x6e2ff3f9529d1a4ed6b7f015ae74800fb745a04c"
      state: "present"

  - name: "updating APT cache"
    apt:
      cache_valid_time: 1800
      update_cache: yes

  # PIP is needed to install Python modules.
  # Ansible needs some Python modules like psycopg2.
  # psycopg2 needs libpq-dev.
  # nodejs is needed by tilemill
  # npm is package manager for nodejs
  - apt:
      pkg:
      - "apache2"
      - "apt-file"
      - "build-essential"
      - "iptables-persistent"
      - "libapache2-mod-tile"
      - "libffi-dev"
      - "libmapnik3.0"
      - "libmapnik-dev"
      - "libpq-dev"
      - "mapnik-utils"
      #- "node-carto"
      #- "nodejs"
      #- "npm"
      - "openstreetmap-carto"
      - "openstreetmap-carto-common"
      - "osm2pgsql"
      - "osmosis"
      - "postgresql-12"
      - "postgresql-12-postgis-3"
      - "python-pip"
      - "renderd"
      - "ruby"
      - "ruby-dev"
      - "time"
      - "zlib1g-dev"
