#!/usr/bin/ansible-playbook
---
- name: "Updates all Ubuntu-APT-Packages"
  hosts: all
  user: root
  tasks:
  - assert:
      msg: "Use --limit!"
      that: "ansible_limit is defined"

  - apt:
      pkg:
      - "cups"
      - "cups-client"
      - "cups-common"
      - "cups-filters"
      - "cups-ppdc"
      - "libcupsfilters1"
      - "libcupsimage2"
      - "postfix"
      - "python3-cups"
      - "rpcbind"
      - "ruby-bundler"
      - "wireshark"
      state: "absent"
    register: "apt"

  - debug:
      var: "apt"

  - name: "autoclean"
    apt:
      autoclean: yes

  - name: "autoremove"
    apt:
      autoremove: yes
