#!/usr/bin/ansible-playbook
---
- name: "Grants rights to PostgreSQL DB users"
  hosts: "all"
  user: "root"
  become: true
  become_user: "postgres"
  tasks:
  - assert:
      msg: "Use --limit!"
      that: "ansible_limit is defined"


  # importeur user
  - name: "GRANT CONNECT ON DATABASE ... TO importeur"
    postgresql_privs:
      db: "{{db.name}}"
      type: "database"
      role: "importeur"
      privs: "CONNECT"
  # osm2pgsql creates tables
  - name: "GRANT CREATE, USAGE ON SCHEMA public TO importeur"
    postgresql_privs:
      db: "{{db.name}}"
      type: "schema"
      objs: "public"
      role: "importeur"
      privs: "CREATE,USAGE"
  - name: "GRANT INSERT, UPDATE, DELETE, TRUNCATE, SELECT ON charge_types TO importeur"
    postgresql_privs:
      db: "{{db.name}}"
      type: "table"
      objs: "charge_types"
      role: "importeur"
      privs: "INSERT,UPDATE,DELETE,TRUNCATE,SELECT"
  - name: "GRANT SELECT ON notices_wgs84"
    postgresql_privs:
      db: "{{db.name}}"
      type: "table"
      objs: "notices_wgs84"
      role: "importeur"
      privs: "SELECT"

  # railsapp user
  - name: "GRANT CONNECT ON DATABASE ... TO railsapp"
    postgresql_privs:
      db: "{{db.name}}"
      type: "database"
      role: "railsapp"
      privs: "CONNECT"
  - name: "GRANT USAGE ON SCHEMA public TO railsapp"
    postgresql_privs:
      db: "{{db.name}}"
      type: "schema"
      objs: "public"
      role: "railsapp"
      privs: "USAGE"
  - name: "GRANT SELECT ON ... TO railsapp"
    postgresql_privs:
      db: "{{db.name}}"
      type: "table"
      role: "railsapp"
      obj: "{{item}}"
      privs: "SELECT"
    loop:
      - "notices_wgs84"
      - "de_falschparker_webm"
      - "simple_boundaries"
      - "charge_types"
      - "schema_migrations"

  # renderd user
  - name: "GRANT CONNECT ON DATABASE ... TO renderd"
    postgresql_privs:
      db: "{{db.name}}"
      type: "database"
      role: "renderd"
      privs: "CONNECT"
  - name: "GRANT USAGE ON SCHEMA public TO renderd"
    postgresql_privs:
      db: "{{db.name}}"
      type: "schema"
      objs: "public"
      role: "renderd"
      privs: "USAGE"
  - name: "GRANT SELECT ON ... TO renderd"
    postgresql_privs:
      db: "{{db.name}}"
      type: "table"
      role: "renderd"
      obj: "{{item}}"
      privs: "SELECT"
    loop:
      - "notices_webm"
      - "de_falschparker_level2_webm"
      - "de_falschparker_level4_webm"
      - "de_falschparker_level5_webm"
      - "de_falschparker_level6_webm"
      - "de_falschparker_level7_webm"
      - "de_falschparker_level8_webm"
      - "de_falschparker_level9_webm"
      - "de_falschparker_level10_webm"
      - "de_falschparker_level11_webm"
      - "de_falschparker_level12_webm"
