#!/usr/bin/ansible-playbook
---
- name: "Drops PostgreSQL DB"
  hosts: "all"
  user: "root"
  become: true
  become_user: "postgres"
  tasks:
  - fail:
      msg: "Use --limit!"
    when: "ansible_limit is not defined"

  - postgresql_db:
      name: "{{db.name}}"
      state: "absent"
