#!/usr/bin/ansible-playbook
---
- name: "Creates PostgreSQL DB"
  hosts: "all"
  user: "root"
  become: true
  become_user: "postgres"
  tasks:
  - assert:
      msg: "Use --limit!"
      that: "ansible_limit is defined"

  - postgresql_db:
      name: "{{db.name}}"

  # by default everyone can create objects in the 'public' schema
  # REVOKE
  - name: "Lock down PUBLIC schema"
    postgresql_privs:
      db: "{{db.name}}"
      state: "absent"
      type: "schema"
      objs: "public"
      privs: "CREATE,USAGE"
      role: "PUBLIC"

  # REVOKE
  - name: "Lock down DB"
    postgresql_privs:
      db: "{{db.name}}"
      state: "absent"
      type: "database"
      privs: "CONNECT,TEMPORARY"
      role: "PUBLIC"
