#!/usr/bin/ansible-playbook
---
- name: "Modify PostgreSQL pg_hba.conf"
  hosts: "all"
  user: "root"
  tasks:
  - fail:
      msg: "Use --limit!"
    when: "ansible_limit is not defined"

  # module not found! :-( 
  #- postgresql_pg_hba:
  #    path: "/etc/postgresql/12/main/pg_hba.conf"
  #    contype: "local"
  #    database: "gis"
  #    users: "railsapp,importeur"
  #    method: "peer"
  #    backup: yes

  - set_fact:
      block1: |
        local   gis             railsapp,importeur                      peer
        host    gis             renderd         samehost                md5

  - set_fact:
      block2: |
        host    all             postgres        samenet                 md5

  - set_fact:
      block: "{{block1}}{% if db.remote_access %}{{block2}}{% endif %}"

  - name: "add lines to pg_hba.conf"
    blockinfile:
      dest: "/etc/postgresql/12/main/pg_hba.conf"
      block: "{{block}}"
      backup: yes
    become: true
    become_user: "postgres"
    register: "blockinfile"

  - name: "restart PostgreSQL"
    systemd:
      name: "postgresql"
      state: "restarted"
    when: "blockinfile.changed"
