#!/usr/bin/ansible-playbook
---
- name: "Changes Password of DB user postgres"
  hosts: "all"
  user: "root"
  become: true
  become_user: "postgres"
  tasks:
  - fail:
      msg: "Use --limit!"
    when: "ansible_limit is not defined"

  # a misspelled module name, or incorrect module?
  # I have ansible 2.5.1, module available in version 2.8
  #- name: "ALTER USER"
  #  postgresql_query:
  #    db: "gis"
  #    query: "ALTER USER postgres WITH ENCRYPTED PASSWORD '{{db.postgres_password}}'"
  #  when: "db.remote_access and db.postgres_password is defined"
  #
  - name: "postgres super user"
    postgresql_user:
      db: "gis"
      name: "postgres"
      password: "{{db.postgres_password}}"
      encrypted: yes
      role_attr_flags: "LOGIN,SUPERUSER,INHERIT,CREATEDB,CREATEROLE,REPLICATION"
    when: "db.remote_access and db.postgres_password is defined"  
