#!/usr/bin/ansible-playbook
---
- name: "add PostgreSQL extension"
  hosts: "all"
  user: "root"
  become: true
  become_user: "postgres"
  tasks:
  - assert:
      msg: "Use --limit!"
      that: "ansible_limit is defined"

  - postgresql_ext:
      db: "{{db.name}}"
      name: "postgis"
