#!/usr/bin/ansible-playbook
---
- name: "Sets or changes 'postgres' super user password"
  hosts: "all"
  user: "root"
  become: true
  become_user: "postgres"
  tasks:
  - assert:
      msg: "Use --limit!"
      that: "ansible_limit is defined"

  # a misspelled module name, or incorrect module?
  # I have ansible 2.5.1, module available since version 2.8
  #- name: "ALTER USER"
  #  postgresql_query:
  #    db: "gis"
  #    query: "ALTER USER postgres WITH ENCRYPTED PASSWORD '{{db.postgres_password}}'"
  #  when: "db.remote_access and db.postgres_password is defined"

  - fail:
    when: "db.remote_access and not db.users.postgres.password is defined" 
 
  - name: "postgres super user"
    postgresql_user:
      db: "{{db.name}}"
      name: "postgres"
      password: "{{db.users.postgres.password}}"
      encrypted: yes
      role_attr_flags: "LOGIN,SUPERUSER,INHERIT,CREATEDB,CREATEROLE,REPLICATION"
    when: "db.remote_access"
