#!/usr/bin/ansible-playbook
---
- name: "Creates PostgreSQL DB user accounts"
  hosts: "all"
  user: "root"
  become: true
  become_user: "postgres"
  tasks:
  - assert:
      msg: "Use --limit!"
      that: "ansible_limit is defined"
 
  - name: "users without password / unix socket connect only"
    postgresql_user:
      db: "{{db.name}}"
      name: "{{item}}"
    loop:
      - "importeur"
      - "railsapp"

  # renderd can't connect via unix socket
  - name: "users with password"
    postgresql_user:
      db: "{{db.name}}"
      name: "renderd"
      password: "{{db.users.renderd.password}}"
      encrypted: yes
