#!/usr/bin/ansible-playbook
---
- name: "Installs required Python modules for Ansible"
  hosts: all
  user: root
  tasks:
  - assert:
      msg: "Use --limit!"
      that: "ansible_limit is defined"

  - pip:
      name: "psycopg2" 
