#!/usr/bin/ansible-playbook
---
- name: "Installs/Updates /etc/renderd.conf"
  hosts: "all"
  user: "root"
  tasks:
  - assert:
      msg: "Use --limit!"
      that: "ansible_limit is defined"
        
  - template:
      src: "../map/renderd.conf.j2"
      dest: "/etc/renderd.conf"
      mode: 0644
      backup: yes
    register: "t"

  - name: "Restart renderd"
    command:
      cmd: "/bin/systemctl restart renderd"
    when: "t.changed"
    register: "r"

  - debug:
      var: "r"
    when: "t.changed"
