#!/usr/bin/ansible-playbook
---
- name: "Installs TileMill, map stylesheets editor (carto CSS coverter is included)"
  hosts: "all"
  user: "root"
  tasks:
  - assert:
      msg: "Use --limit!"
      that: "ansible_limit is defined"
        
  - template:
      src: "../map/renderd.conf.j2"
      dest: "/etc/renderd.conf"
      mode: 0644
