#!/usr/bin/ansible-playbook
---
- name: "Installs required Ruby gems/modules"
  hosts: "all"
  user: "root"
  tasks:
  - assert:
      msg: "Use --limit!"
      that: "ansible_limit is defined"

  - gem:
      name: "{{item}}"
      user_install: no
      #name: "rails,bundler,nokogiri,pg"
    loop:
      - "rails"
      - "pg" 
