#!/usr/bin/ansible-playbook
---
- name: "removes passords from tilemill project and copies it to git repository"
  hosts: "all"
  user: "root"
  become: true
  become_user: "importeur"
  vars:
    script: "mapstyle_tilemill_to_template.py"
    project_dir: "/home/importeur/Documents/MapBox/project/falschparker"
  tasks:
  - assert:
      msg: "Use --limit!"
      that: "ansible_limit is defined"

  - copy:
      src: "../map/{{script}}"
      dest: "/home/importeur/{{script}}"
      mode: 0760

  - name: "convert project file to template"
    shell:
      cmd: "/home/importeur/{{script}} <{{project_dir}}/project.mml >{{project_dir}}/project.mml.j2"
    register: "cmd"

  - debug:
      var: "cmd"

  - fetch:
      src: "{{project_dir}}/project.mml.j2"
      dest: "../map/style/project.mml.j2"
      flat: yes

  - fetch:
      src: "{{project_dir}}/style.mss"
      dest: "../map/style/style.mms"
      flat: yes
