#!/usr/bin/ansible-playbook
---
- name: "installs or updates tilemill project"
  hosts: "all"
  user: "root"
  become: true
  become_user: "importeur"
  vars:
    project_dir: "/home/importeur/Documents/MapBox/project/falschparker"
    db_host: "localhost"
    db_port: 5432
    db_user: "renderd"
    db_password: "{{db.users.renderd.password}}"
  tasks:
  - assert:
      msg: "Use --limit!"
      that: "ansible_limit is defined"

  - copy:
      src: "../map/style/style.mss"
      dest: "{{project_dir}}/style.mss"
      mode: 0660

  - template:
      src: "../map/style/project.mml.j2"
      dest: "{{project_dir}}/project.mml"
