#!/usr/bin/ansible-playbook
---
- name: "Installs TileMill, map stylesheets editor (carto CSS converter is included)"
  hosts: "all"
  user: "root"
  become: true
  become_user: "importeur"
  tasks:
  - assert:
      msg: "Use --limit!"
      that: "ansible_limit is defined"
        
  - name: "Download TileMill from github"
    git:
      repo: "https://github.com/tilemill-project/tilemill.git"
      dest: "/home/importeur/tilemill"

  - name: "install NodeJS packages"
    command:
      cmd: "npm install"
    args:
      chdir: "/home/importeur/tilemill"
    register: "npm_install"

  - debug:
      var: "{{item}}"
    loop:
      - "npm_install.stdout_lines"
      - "npm_install.stderr_lines"
