#!/usr/bin/ansible-playbook
---
- name: "installs or updates tilemill project"
  hosts: "all"
  user: "root"
  become: true
  become_user: "importeur"
  vars:
    project_dir: "/home/importeur/Documents/MapBox/project/falschparker"
    ds_host: "localhost"
    ds_port: 5432
    ds_user: "renderd"
    ds_password: "{{db.users.renderd.password}}"
  tasks:
  - assert:
      msg: "Use --limit!"
      that: "ansible_limit is defined"

  - name: "copy style.mss"
    copy:
      src: "../map/style/style.mss"
      dest: "{{project_dir}}/style.mss"
      mode: 0660
      backup: yes

  - name: "template project.mml.j2" 
    template:
      src: "../map/style/project.mml.j2"
      dest: "{{project_dir}}/project.mml"
      mode: 0660
      backup: yes
